name: Python Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        
    - name: Run unit tests Fib
      run: python -m unittest ./tests/test_fibonacci.py -v
      
    - name: Run unit tests bmi
      run: python -m unittest ./tests/test_bmi_calculator.py -v
    
    - name: Run unit tests two_number_sum
      run: python -m unittest ./tests/test_two_number_sum.py -v

    - name: Run unit tests sorted_square_array
      run: python -m unittest ./tests/test_sorted_square_array.py -v
    - name: Run unit tests validate_subsequence
      run: python -m unittest ./tests/test_validate_subsequence.py -v
    
      
